config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :accounts do
    collection do
  	  get 'archive'
  	end
  	member do
  	  get :restore
  	end
  end
  patch 'accounts' => 'accounts#destroy'
  
  resources :admin
  get 'admin', to: 'admin#index'
  
  get 'login', to: 'login#index', as: 'login'
  get 'logout', to: 'login#destroy', as: 'logout'
  # Routes for Google authentication
  get 'auth/google_oauth2/callback', to: 'login#create'
  get 'auth/failure', to: redirect('/')

  get 'passenger', to: 'passenger#index'
  get 'driver', to: 'driver#index'

  match 'passenger', to: 'passenger#create', via: [:post]
  match 'driver', to: 'driver#create', via: [:post]

  resources :rides
  get 'rides/:ride_id' => 'rides#contact'
  delete 'rides/:ride_id' => 'rides#destroy'
  resources :services
  
  resources :profile
  get '*path' => redirect('/home/index')
end

app/views/admin/index.html.erb
<center>
  <h1>Dashboard</h1>
  <!--<table class="center">
	<tr>
	  <td>
		<%= link_to '<button type="submit" class="btn btn-primary" style="margin-bottom: 10px">Accounts</button>'.html_safe, accounts_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%= link_to '<button type="submit" class="btn btn-primary">Posts</button>'.html_safe, rides_path %>
	  </td>
  </tr>
  </table>-->

  <div class="card-deck">
    <div class="card bg-light">
      <%= link_to(accounts_path, :class => "clickable-card") do %>
        <%= image_tag('group.jpg', :class => "card-img-top", :size => '100x200') %>
        <div class="card-body">
          <h5 class="card-title">Active Accounts</h5>
          <p class="card-text">Manage and remove active user accounts.</p>
        </div>
      <% end %>
    </div>

    <div class="card bg-light">
      <%= link_to(archive_accounts_path, :class => "clickable-card") do %>
        <%= image_tag('shelf.jpg', :class => "card-img-top", :size => '100x200') %>
        <div class="card-body">
          <h5 class="card-title">Archived Accounts</h5>
          <p class="card-text">View and restore archived user accounts.</p>
        </div>
      <% end %>
    </div>

    <div class="card bg-light">
      <%= link_to(rides_path, :class => "clickable-card") do %>
        <%= image_tag('transport.jpg', :class => "card-img-top", :size => '100x200') %>
        <div class="card-body">
          <h5 class="card-title">Posts</h5>
          <p class="card-text">Manage and remove user rides and posts.</p>
        </div>
      <% end %>
    </div>

  </div>

  </div>
</center>

</br>