config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :accounts do
    collection do
  	  get 'archive'
  	end
  	member do
  	  get :restore
  	end
  end
  patch 'accounts' => 'accounts#destroy'
  
  resources :admin
  get 'admin', to: 'admin#index'
  
  get 'login', to: 'login#index', as: 'login'
  get 'logout', to: 'login#destroy', as: 'logout'
  # Routes for Google authentication
  get 'auth/google_oauth2/callback', to: 'login#create'
  get 'auth/failure', to: redirect('/')

  get 'passenger', to: 'passenger#index'
  get 'driver', to: 'driver#index'

  match 'passenger', to: 'passenger#create', via: [:post]
  match 'driver', to: 'driver#create', via: [:post]

  resources :rides
  get 'rides/:ride_id' => 'rides#contact'
  delete 'rides/:ride_id' => 'rides#destroy'
  resources :services
  
  resources :profile
  get '*path' => redirect('/home/index')
end

app/models/ride.rb
require 'pry'

class Ride < ApplicationRecord
  belongs_to :account
  validates :role, presence: true, inclusion: { in: %w[driver passenger] }
  validates :departure, presence: { message: "Please select a valid departure location from Google Maps"}
  validates :destination, presence: { message: "Please select a valid destination location from Google Maps"}

  validates :start_date, presence: { message: "Please select a departure date"},
                         timeliness: { :type => :date, :message => "Please select a departure date in the future" }

  validates :start_time, presence: { message: "Please enter a starting departure time"},
                         timeliness: { :type => :time, message: "Please enter starting departure time in correct format(i.e. 07:00), after current time" }

  validates :end_time, presence: { message: "Please enter a ending departure time"},
                       timeliness: { :type => :time, :message => "Please enter ending departure time in correct format(i.e. 07:00), after the starting time" }

  validates :seats, presence: { message: "Please enter a seat number"},
                    inclusion: { in: 1..8, message: "Please enter a seat number that is between 1-8" }

  validates :departure_lat, presence: { message: "Location coordinates cannot be found."}
  # validates :departure_lon, presence: { message: "Please select a valid departure location from Google Maps."}
  validates :destination_lat, presence: { message: "Location coordinates cannot be found."}
  # validates :destination_lon, presence: { message: "Please select a valid destination location from Google Maps."}

  validates :start_datetime, timeliness: { :on_or_after => :now }
  validates :end_datetime, timeliness: { :on_or_after => :start_datetime }

  before_validation :geocode_departure, if: ->(obj){ obj.departure.present? and obj.departure_changed? }
  before_validation :geocode_destination, if: ->(obj){ obj.destination.present? and obj.destination_changed? }
  before_validation :parse_datetime

  def start_date=(value)
    value = Date.strptime(value, '%m/%d/%Y') rescue value
    super(value)
  end

  def end_date=(value)
    value = Date.strptime(value, "%m/%d/%Y") rescue value
    super(value)
  end

  def self.all_types
    %w(driver passenger)
  end

  def parse_datetime
    self.start_time = self.start_time.strip rescue nil
    self.end_time = self.end_time.strip rescue nil
    if self.end_date.nil?
      self.end_date = self.start_date
    end

    self.start_time = Timeliness.parse(self.start_time).strftime('%H:%M') rescue self.start_time
    self.end_time = Timeliness.parse(self.end_time).strftime('%H:%M') rescue self.end_time

    self.start_datetime = Timeliness.parse("#{self.start_date} #{self.start_time}") rescue nil
    self.end_datetime = Timeliness.parse("#{self.end_date} #{self.end_time}") rescue nil
  end

  private

  def geocode_departure
    g = Geocoder.search(self.departure)
    self.departure_lat, self.departure_lon = g.first.coordinates rescue [nil, nil]
  end

  def geocode_destination
    g = Geocoder.search(self.destination)
    self.destination_lat, self.destination_lon = g.first.coordinates rescue [nil, nil]
  end



  def self.departure_in_range(location_1, location_2, range) #check if location_2 is location_1's circle with a custom radius
    point1 = [location_1.departure_lat,location_1.departure_lon]
    point2 = [location_2.departure_lat,location_2.departure_lon]
    return Geocoder::Calculations.distance_between(point1, point2) <= range
  end

  def self.destination_in_range(location_1, location_2, range) #check if location_2 is location_1's circle with a custom radius
    point1 = [location_1.destination_lat,location_1.destination_lon]
    point2 = [location_2.destination_lat,location_2.destination_lon]
    return Geocoder::Calculations.distance_between(point1, point2) <= range
  end

  def self.match_ride(id) #    @ride = Ride.find(params[:id])
    @ride = Ride.find(id)
    @matched_rides = Array.new
    Ride.all.each do |potential_match|
      #role show, capacity show
      if potential_match == @ride || @ride.role == potential_match.role
        next
      end
      if @ride.role == 'driver' && potential_match.seats > @ride.seats
        next
      end
      if @ride.role == 'passenger' && potential_match.seats < @ride.seats
        next
      end

      match = {
          :departure => Ride.departure_in_range(potential_match, @ride, 1),
          :destination => Ride.destination_in_range(potential_match, @ride, 1),
          :date => @ride.start_date == potential_match.start_date,
          :time => @ride.start_time <= potential_match.end_time && potential_match.start_time <= @ride.end_time,
          :not_match_own_rides => @ride.account != potential_match.account
      }


      if match.values.all?()
        @matched_rides.push(potential_match)
      end
    end
    return @matched_rides
  end

end

app/controllers/rides_controller.rb
require 'pry'

class RidesController < ApplicationController
  before_action :login_required, :only => [:index, :new, :create, :show, :destroy, :edit, :update]
  before_action :check_not_archived, :only => [:index, :new, :create, :show, :destroy, :edit, :update]


  def index

    @all_types = Ride.all_types
    permitted = params.permit(type: [:driver, :passenger])
    @selected_type = permitted[:type] || session[:type] || {}

    if @selected_type == {}
      # @selected_type = @all_types
      @selected_type = Hash[@all_types.map {|role| [role, 1]}]
    end

    if params[:type] != session[:type]
      session[:type] = @selected_type
      redirect_to :type => @selected_type and return
    end

    if current_user.isAdmin == true
      @rides = Ride.where(:role => @selected_type.keys).order(:start_datetime => 'asc')
    else
      @rides = Ride.joins(:account).where(:role => @selected_type.keys).order(:start_datetime => 'asc').where('start_date >= ?', Date.today).where('accounts.archived != ?', true)
    end

  end

  def new
    if current_user.isAdmin == true
      redirect_to admin_index_path
    else
      @ride = Ride.new
    end
  end

  def create
    # byebug
    @ride = current_user.rides.new(ride_params)
    respond_to do |format|
      if @ride.save
        format.html do
          flash[:notice] = 'Ride successfully created'
          redirect_to controller: 'rides', action: 'show', id: @ride.id
        end

        format.json {render :show, status: :created, location: @ride}
      else
        format.html {render :new}
        format.json {render json: @ride.errors, status: :unprocessable_entity}
      end
    end
  end

  def show
    @ride = Ride.find(params[:id])
    @rides = Ride.match_ride(params[:id])
	rescue ActiveRecord::RecordNotFound
        redirect_to "/home/index"
  end

  def destroy
    Ride.destroy(params[:id])
    respond_to do |format|
      format.html {redirect_to rides_path, notice: 'Ride was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def edit
    # Check if user owns the ride. If not, throw 401 Unauthorized
    @ride = Ride.find(params[:id])
    if not current_user.id == @ride.account_id or current_user.isAdmin == true
      render '401', :status => 401
    end
	rescue ActiveRecord::RecordNotFound
        redirect_to "/home/index"
  end

  def update
    @ride = Ride.find(params[:id])
    if @ride.update_attributes(ride_params)
      @ride.save
      flash[:notice] = "Ride was successfully updated."
      redirect_to profile_index_path
    else
      flash[:alert] = "Field is missing or invalid in the form."
      respond_to do |format|
        format.html {}
        format.js {render js: 'window.top.location.reload();$(document).scrollTop(0);'}
      end
    end
  end

  private

  def ride_params
    params.require(:ride).permit(:role, :departure, :destination, :start_date, :end_date, :start_time, :end_time, :seats)
  end
end

app/views/rides/_form.html.erb
<%= link_to 'Back', rides_path %>

<script>
    $(document).ready(function () {

        $('input.form_type[type=radio]').change(function () {
            $('.driver_form, .passenger_form').addClass('d-none');

            var fieldToShow = $(this).val();

            $(".ride_form").removeClass('d-none');
            $("." + fieldToShow + "_form").removeClass('d-none');
        });

        $('.input-daterange').datepicker({
            format: 'mm/dd/yyyy'
        });
    });
</script>
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", initMap);
  </script>
<% end %>

<% if ride.errors.any? %>
  <div id="error_explanation" class="p-10">
    <h2> The following errors prohibited this ride from being saved:</h2>
    <ul>
      <% ride.errors.messages.each do |message| %>
        <li><%=  "#{message[0]}".first.upcase + "#{message[0][1..-1]}".sub("_", " ") + ": " + "#{message[1][0]}".first.upcase + "#{message[1][0][1..-1]}".sub("_", " ") %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1 class="center">Are you a Driver or Passenger?</h1>
<%= form_with model: ride, local: true, html: {:autocomplete => 'off'} do |f| %>
  <div class="row">
    <div class="offset-2 col-8">
      <div class="p-2 center">
        <div class="btn-group-toggle" data-toggle="buttons">
          <%= f.label :role, "", :for => "Driver", :class => "btn btn-outline-danger" do %>
            <%= f.radio_button :role, 'driver', class: 'form_type form-check-input', id: 'Driver', value: 'driver' %>
            Driver
          <% end %>
          <%= f.label :role, "", :for => "Passenger", :class => "btn btn-outline-danger" do %>
            <%= f.radio_button :role, 'passenger', class: 'form_type form-check-input', id: 'Passenger', value: 'passenger' %>
            Passenger
          <% end %>
        </div>
      </div>
      <div>
        <div>
          <div class="ride_form d-none">
            <div class="driver_form">
              <h1 class="center p-4">Driver Form</h1>
            </div>

            <div class="passenger_form">
              <h1 class="center p-4">Passenger Form</h1>
            </div>

            <div class="center">
              <h5 class="text-secondary"> Type and Select Departure and Destination Location in Google Map</h5>
            </div>

            <div class="d-none">
              <input id="ride_departure" class="controls" type="text" name="ride[departure]"
                     placeholder="Enter an origin location">

              <input id="ride_destination" class="controls" type="text" name="ride[destination]"
                     placeholder="Enter a destination location">
            </div>

            <div id="map"></div>

            <div class="input-daterange row">
              <div class="form-group col-6">
                <%= f.label :start_date, "Departure Date (MM/DD/YYYY)" %>
                <% if !@ride.start_date.blank? %>
                  <%= f.text_field :start_date, :class => "form-control", :value => Date.parse(@ride.start_date).strftime('%m/%d/%Y') %>
                <% else %>
                  <%= f.text_field :start_date, :class => "form-control" %>
                <% end %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-6">
                <%= f.label :start_time, "Departure Time (hh:mm) from" %>
                <%= f.text_field :start_time, :class => "form-control" %>
              </div>
              <div class="form-group col-6">
                <%= f.label :end_date, "Departure Time (hh:mm) to" %>
                <%= f.text_field :end_time, :class => "form-control" %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-6">
                <%= f.label :seats, "How many seats are available?", class: 'driver_form' %>
                <%= f.label :seats, "How many seats do you need?", class: 'passenger_form' %>
                <%= f.number_field :seats, :class => "form-control", :min => "1",:max => "8", :value => "1" %>
              </div>
            </div>
            <div class="center">
              <%= f.submit :class => "btn btn-primary" %>
              <%= button_tag("Reset", type: "reset", class: "btn btn-secondary") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<br>

app/views/rides/contact.html.erb
<%= link_to 'back to all rides', rides_path %>
<br><br>

<div class="center">
  <h1>Contact Information</h1>
</div>

<table id="rides-table" class="table table-striped">
  <thead>
  <tr>
    <th>Username</th>
    <th>Email</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><%= @contact.username %></td>
    <td><%= @contact.email %></td>
  </tr>
  </tbody>
</table>

<div class="center">
  <h1>Ride Information</h1>
</div>
<table id="rides-table" class="table table-striped">
  <thead>
  <tr>
    <th>Creator Username</th>
    <th>Type</th>
    <th>Departure</th>
    <th>Destination</th>
    <th>Departure Date</th>
    <th>Departure Time</th>
    <th>Seats</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% r = @ride %>
  <tr>
    <td><%= link_to "Ride " + String(r.id), r %></td>
    <td><%= r.role %></td>
    <td><%= r.departure %></td>
    <td><%= r.destination %></td>
    <td><%= String(r.start_date) + " to " + String(r.end_date) %></td>
    <td><%= String(r.start_time) + " to " + String(r.end_time) %></td>
    <td><%= r.seats %></td>
    <td><%= link_to "Show", r, class: 'badge-pill badge-info' %>
      <% if session.has_key?('login') and current_user.isAdmin == true %>
        <%= link_to "Delete", ride_path(r), method: :delete, data: {confirm: "Are you sure?"}, class: 'badge-pill badge-danger' %></td>
      <% end %>
      </tr>
  </tbody>
</table>
<br>

app/views/rides/edit.html.erb
<%= link_to 'Back', profile_index_path %>
<script>
    $(document).ready(function () {

        $('input.form_type[type=radio]').change(function () {
            $('.driver_form, .passenger_form').addClass('d-none');
            var fieldToShow = $(this).val();
            $(".ride_form").removeClass('d-none');
            $("." + fieldToShow + "_form").removeClass('d-none');
        });
        $('.input-daterange').datepicker({
            format: 'mm/dd/yyyy'
        });


    });
</script>
<% provide :head_tags do %>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", initMap);
  </script>
<% end %>
<%= form_with model: @ride, html: {:autocomplete => 'off'} do |f| %>
  <div class="row">
    <div class="offset-2 col-8">
      <div>
        <div>
          <div class="ride_form">
            <% if @ride.role == "driver" %>
              <div class="driver_form">
                <h1 class="center">Edit Driver Form</h1>
              </div>
            <% elsif @ride.role == "passenger" %>
              <div class="passenger_form">
                <h1 class="center">Edit Passenger Form</h1>
              </div>
            <% end %>
            <div class="row">
              <div class="column col-6">
                <%= f.label :id, "Ride ID" %>
                <%= f.text_field :id, class: 'form-control', id: 'id', :readonly => "readonly" %>
              </div>
              <div class="column col-6">
                <%= f.label :role, "Role" %>
                <%= f.text_field :role, class: 'form-control', id: 'role', :readonly => "readonly" %>
              </div>
            </div>
            <br>
            <div>
              <input id="ride_departure" class="controls" type="text" name="ride[departure]" value="<%= @ride.departure %>">

              <input id="ride_destination" class="controls" type="text" name="ride[destination]" value="<%= @ride.destination %>">
            </div>

            <div id="map"></div>
            <div class="input-daterange row">
              <div class="form-group col-6">
                <%= f.label :start_date, "Departure Date (MM/DD/YYYY)" %>
                <%= f.text_field :start_date, :class => "form-control", :value => Date.parse(@ride.start_date).strftime('%m/%d/%Y') %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-6">
                <%= f.label :start_time, "Departure Time (hh:mm) from" %>
                <%= f.text_field :start_time, :class => "form-control" %>
              </div>
              <div class="form-group col-6">
                <%= f.label :end_date, "Departure Time (hh:mm) to" %>
                <%= f.text_field :end_time, :class => "form-control" %>
              </div>
            </div>
            <div class="row">
              <div class="form-group col-6">
                <% if @ride.role == "driver" %>
                  <%= f.label :seats, "How many seats are available?", class: 'driver_form' %>
                <% elsif @ride.role == "passenger" %>
                  <%= f.label :seats, "How many seats do you need?", class: 'passenger_form' %>
                <% end %>
                <%= f.number_field :seats, :class => "form-control", :min => "1" %>
              </div>
            </div>
            <div class="center">
              <% %>
              <%= f.submit :class => "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<br>

app/views/rides/index.html.erb
<% if session.has_key?('login') and current_user.isAdmin == true %>
  <%= link_to 'Back to Dashboard Page', admin_index_path %>
<% elsif session.has_key?('login') %>
  <div>
    <%= link_to 'Back to Services Page', services_path %>
  </div>
<% end %>
<div class="center">
  <h1>All Rides Offers/Requests</h1>
</div>

<% if current_user.isAdmin == false %>
  <div class="center p-3">
    <%= link_to 'Create Ride', new_ride_url, class: "btn btn-primary " %>
  </div>
<% end %>

<div class="float-right p-3">
  <%= form_tag rides_path, :method => :get, :id => 'ride_type_form' do %>
    <%= hidden_field_tag "date_sort", true if @date_header %>
    <%= hidden_field_tag "time_sort", true if @time_header %>
    Ride Type:

    <% Ride.all_types.each do |role| %>
      <%= label_tag("role_#{role}", role) %>
      <%= check_box_tag "type[#{role}]", 1, @selected_type.include?(role), :id => "role_#{role}" %>
    <% end %>

    <%= submit_tag 'Refresh', :id => 'ride_type_submit', :class => 'btn btn-outline-danger btn-sm' %>
  <% end %>
</div>


<table id="rides-table" class="table table-striped">
  <thead>
  <tr>
    <th>Creator Username</th>
    <th>Type</th>
    <th>Departure</th>
    <th>Destination</th>
    <th>Departure Date</th>
    <th>Departure Time</th>
    <th>Seats</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @rides.each do |r| %>
    <tr>
      <td><%= r.account.username %></td>
      <td><%= r.role %></td>
      <td><%= r.departure %></td>
      <td><%= r.destination %></td>
      <td><%= String(Date.parse(r.start_date).strftime('%m/%d/%Y')) %></td>
      <td><%= String(r.start_time) + " to " + String(r.end_time) %></td>
      <td><%= r.seats %></td>
      <% if session.has_key?('login') and current_user.isAdmin == true %>
        <td>
		<!--<%= button_tag "Delete", {class: 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => "#delete-ride-#{r.id}"} %>-->
        <%= link_to "Delete", ride_path(r), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %></td>
      <% elsif session.has_key?('login') %>
        <td><%= button_tag "Contact #{r.role.capitalize}", {class: 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => "#delete-ride-#{r.id}"} %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<% @rides.each do |r| %>
  <!-- Modal -->
  <div class="modal fade" id="delete-ride-<%= r.id %>" tabindex="-1" role="dialog" aria-labelledby="delete-modal-<%= r.id %>-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="delete-modal-<%= r.id %>-label"><%= "#{r.role.capitalize}" %> Information</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>

        <div class="modal-body">
          <table class="table table-bordered thead-light ">
            <tbody>
            <tr>
              <th><%= "#{r.role.capitalize}" %> Username</th>
              <td class="table-light"><%= "#{r.account.username}" %> </td>
            </tr>
            <tr>
              <th><%= "#{r.role.capitalize}" %> Email</th>
              <td class="table-light"><%= "#{r.account.email}" %> </td>
            </tr>
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <% if session.has_key?('login') and current_user.isAdmin == true %>
            <%= link_to "Confirm Delete", ride_path(r), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/rides/new.html.erb
<%= render 'form', ride: @ride %>
<br>

app/views/rides/show.html.erb
<%= link_to 'View all rides', rides_path %>
<br><br>

<div class="center">
  <h1>Auto-Matched Rides</h1>
</div>

<div class="trip-info text-secondary center p-2">
  <div class="row center">
    <span class="center">For your trip from <b><%= "#{@ride.departure}" %></b></span>
  </div>
  <div class="row center">
    <span class="center">To <b><%= "#{@ride.destination}" %></b></span>
  </div>
  <div class="row center">
    <span class="center">Starting at <b><%= "#{Date.parse(@ride.start_date).strftime('%m/%d/%Y')}" %> </b><b><%= "#{@ride.start_time}" %> </b> to
      <b><%= "#{Date.parse(@ride.end_date).strftime('%m/%d/%Y')}" %></b> <b><%= "#{@ride.end_time}" %> </b></span>
  </div>
</div>

<% if @rides.size == 0 %>
  <div class="center p-4">
    <%= image_tag('sorry.png', :class => "", :width => '100', :height => '100') %>
    <h3> Sorry, we currently don't have any match </h3>
    <h5 class="text-secondary"> Please check this ride on your profile later</h5>
  </div>

<% else %>
  <table id="rides-table" class="table table-striped">
    <thead>
    <tr>
      <th>Creator Username</th>
      <th>Type</th>
      <th>Departure</th>
      <th>Destination</th>
      <th>Departure Date</th>
      <th>Departure Time</th>
      <th>Seats</th>
      <th>Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @rides.each do |r| %>
      <tr>
        <td><%= r.account.username %></td>
        <td><%= r.role %></td>
        <td><%= r.departure %></td>
        <td><%= r.destination %></td>
        <td><%= String(Date.parse(r.start_date).strftime('%m/%d/%Y')) %></td>
        <td><%= String(r.start_time) + " to " + String(r.end_time) %></td>
        <td><%= r.seats %></td>
        <% if session.has_key?('login') and current_user.isAdmin == true %>
          <td><%= button_tag "delete", {class: 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => "#delete-ride-#{r.id}"} %></td>
        <% elsif session.has_key?('login') %>
          <td><%= button_tag "Contact #{r.role.capitalize}", {class: 'btn btn-primary', 'data-toggle' => 'modal', 'data-target' => "#delete-ride-#{r.id}"} %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>

  <% @rides.each do |r| %>
    <!-- Modal -->
    <div class="modal fade" id="delete-ride-<%= r.id %>" tabindex="-1" role="dialog" aria-labelledby="delete-modal-<%= r.id %>-label" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="delete-modal-<%= r.id %>-label"><%= "#{r.role.capitalize}" %> Information</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <div class="modal-body">
            <table class="table table-bordered thead-light ">
              <tbody>
              <tr>
                <th><%= "#{r.role.capitalize}" %> Username</th>
                <td class="table-light"><%= "#{r.account.username}" %> </td>
              </tr>
              <tr>
                <th><%= "#{r.role.capitalize}" %> Email</th>
                <td class="table-light"><%= "#{r.account.email}" %> </td>
              </tr>
              </tbody>
            </table>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <% if session.has_key?('login') and current_user.isAdmin == true %>
              <%= link_to "Delete", ride_path(r), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>