config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :accounts do
    collection do
  	  get 'archive'
  	end
  	member do
  	  get :restore
  	end
  end
  patch 'accounts' => 'accounts#destroy'
  
  resources :admin
  get 'admin', to: 'admin#index'
  
  get 'login', to: 'login#index', as: 'login'
  get 'logout', to: 'login#destroy', as: 'logout'
  # Routes for Google authentication
  get 'auth/google_oauth2/callback', to: 'login#create'
  get 'auth/failure', to: redirect('/')

  get 'passenger', to: 'passenger#index'
  get 'driver', to: 'driver#index'

  match 'passenger', to: 'passenger#create', via: [:post]
  match 'driver', to: 'driver#create', via: [:post]

  resources :rides
  get 'rides/:ride_id' => 'rides#contact'
  delete 'rides/:ride_id' => 'rides#destroy'
  resources :services
  
  resources :profile
  get '*path' => redirect('/home/index')
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<style>
  .navbar-brand {
    font-size: 2em;
  }
</style>

<nav class="navbar navbar-light" style="background-color: #BC0813">

  <div class="container">
    <div>

        <%= link_to home_index_path, class: 'navbar-brand' do %>
          <%= image_tag "cssa.png", :width => "60", :height => "60", :id => "site-logo" %>
          <div style="color:white; display:inline">CSSA Hub!</div>
		  <% end %>
    </div>

    <div class="dropdown">
      <button class="btn btn-light dropdown-toggle" style="color: #BC0813" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if session.has_key?('login') and session['login'] %>
          <%= "Welcome, #{session['login']}" %>
        <% else %>
          Menu
        <% end %>
      </button>

      <div class="dropdown-menu my-2" aria-labelledby="dropdownMenuButton">
        <% if session.has_key?('login') and session['login'] %>
		<% if current_user.isAdmin %>
            <%= link_to "Dashboard", admin_index_path, :class => "dropdown-item"%>
		<% end %>
          <% if not current_user.isAdmin %>
            <%= link_to "Profile", profile_index_path, :class => "dropdown-item" %>
		    <%= link_to "Services", services_path, :class => "dropdown-item" %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", logout_path, :class => "dropdown-item" %>
        <% else %>
          <%= link_to "Login", login_path, :class => "dropdown-item logout-link" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>CSSA Hub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+ENV['MAPS_API_KEY']+"&libraries=places" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> 'reload' %>
    <%= stylesheet_link_tag    'https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.8.0/dist/css/bootstrap-datepicker.standalone.min.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track'=> 'reload' %>
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js' %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.bundle.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/bootstrap-datepicker@1.8.0/dist/js/bootstrap-datepicker.min.js" %>
    <%= yield(:head_tags) %>
  </head>
  
  <body>
      <header>
        <%= render 'layouts/navigation' %>
      </header>
    <div class="container">
      <main role="main">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </main>
    </div>
    <script>document.querySelector('form').onkeypress = checkEnter;</script>
  </body>
</html>