config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'

  resources :accounts do
    collection do
  	  get 'archive'
  	end
  	member do
  	  get :restore
  	end
  end
  patch 'accounts' => 'accounts#destroy'
  
  resources :admin
  get 'admin', to: 'admin#index'
  
  get 'login', to: 'login#index', as: 'login'
  get 'logout', to: 'login#destroy', as: 'logout'
  # Routes for Google authentication
  get 'auth/google_oauth2/callback', to: 'login#create'
  get 'auth/failure', to: redirect('/')

  get 'passenger', to: 'passenger#index'
  get 'driver', to: 'driver#index'

  match 'passenger', to: 'passenger#create', via: [:post]
  match 'driver', to: 'driver#create', via: [:post]

  resources :rides
  get 'rides/:ride_id' => 'rides#contact'
  delete 'rides/:ride_id' => 'rides#destroy'
  resources :services
  
  resources :profile
  get '*path' => redirect('/home/index')
end

app/models/account.rb
require 'pry'

class Account < ApplicationRecord
  has_many :rides
  
  validates :email, presence: true, format: { with: /\A\S+@tamu.edu\z/, message: "must be tamu email" }, uniqueness: true
  validates :username, presence: true
  
  def self.from_omniauth(auth)
    if account = Account.find_by_email(auth.info.email)
      account
    else
      netid = auth.info.email[ /\A.+?(?=@)/ ]  
      account = Account.create(username: netid, email: auth.info.email)
      account.save
      account
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :login_required, :only => [:index, :show, :edit, :destroy, :update, :archive, :restore]
  before_action :check_not_archived, :only => [:index, :show, :edit, :destroy, :update, :archive, :restore]
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    if (current_user.isAdmin == true)
      @accounts = Account.where(:archived => false).where(isAdmin: false)
	else
      redirect_to services_path, notice: "Logged in!"
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def archive
    if (current_user.isAdmin == true)
      @accounts = Account.where(:archived => true)
	else
      redirect_to services_path, notice: "Logged in!"
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    @profile = Account.find(params[:id])
	  if @profile.update_attributes!(update_params)
	    if @profile.save
        redirect_to profile_index_path, notice: "Account was successfully saved."
      end
    else
      flash[:alert] = "Account failed to save"
      redirect_to profile_index_path
    end
  end
  

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
	@account.reason = params[:account][:reason]
	@account.toggle!(:archived)
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully archived.' }
      format.json { head :no_content }
    end
  end
  
  def restore
	@account = Account.find(params[:id])
    @account.toggle!(:archived)
    respond_to do |format|
      format.html { redirect_to archive_accounts_url, notice: 'Account was successfully restored.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
	  # I made changes to this so if something broke, check here first
	  if params[:id] != nil
        @account = Account.find(params[:id])
	  elsif params[:account] != nil
	    @account = Account.find(params[:account][:id])
	  end
	  rescue ActiveRecord::RecordNotFound
        redirect_to "/home/index"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:username, :email, :name)
    end
	
	def update_params
      params.permit(:name)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/archive.html.erb
<% if session.has_key?('login') and current_user.isAdmin == true %>
  <%= link_to 'Back to Dashboard', admin_index_path %>
<% end %>

<div class="center">
  <h1>Archived Accounts</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Reason for Deletion</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td style="width:auto"><%= account.username %></td>
        <td><%= account.name %></td>
        <td><%= account.email %></td>
        <td><%= account.reason %></td>
        <td>
          <button class="btn btn-primary" data-toggle="modal" data-target="#restoreForm-<%= account.username %>" id="restore-<%= account.username %>">Restore
            User
          </button>
        </td>


        <div class="modal fade" id="restoreForm-<%= account.username %>">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Confirm Restoration</h5>
                <button type="button" class="close" data-dismiss="modal">
                  <span>&times;</span>
                </button>
              </div>

              <form>
                <div class="modal-body">

                  <h5>Restore user: <%= account.username %></h5>
                  <p>Are you sure you want to restore this user's account?</p>
                </div>

                <div class="modal-footer">
                  <%= link_to restore_account_path(account), :id => "confirmRestore-" + account.username do %>
                    <button type="submit" class="btn btn-primary">Restore</button>
                  <% end %>
                </div>
              </form>

            </div>
          </div>
        </div>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/index.html.erb
<% if session.has_key?('login') and current_user.isAdmin == true %>
  <%= link_to 'Back to Dashboard', admin_index_path %>
<% end %>

<div class="center">
  <h1>Active Accounts</h1>

  <table class="table table-striped">
    <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Created On</th>
      <th colspan="3">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td style="width:auto"><%= account.username %></td>
        <td><%= account.name %></td>
        <td><%= account.email %></td>
        <td><%= account.created_at.strftime("%m/%d/%Y") %></td>
        <td>
          <button class="btn btn-danger" data-toggle="modal" data-target="#archiveForm-<%= account.username %>" id="archive-<%= account.username %>">Archive
            User
          </button>
        </td>

        <td>
          <div class="modal fade" id="archiveForm-<%= account.username %>">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Confirm Archive</h5>
                  <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                  </button>
                </div>

                <%= form_for account, url: {method: :destroy} do |f| %>
                  <div class="modal-body">
                    <h5>Archive user: <%= account.username %></h5>
                    <p>Please enter the reason for suspension:</p>
                    <%= f.text_area :reason, value: "", class: "form-control" %>
                    <%= f.hidden_field :id, value: account.id %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit "Archive", class: "btn btn-danger", id: "confirmArchive-" + account.username %>
                  </div>
                <% end %>

              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>